/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Vehicle carA = new Vehicle("CarA", "BrandA");
        Vehicle carB = new Vehicle("CarB", "BrandB");
        carA.speedUp(10);
        carB.speedUp((50));

    }
}
class Vehicle {
    String name;
    String brand;
    public Vehicle(String name, String brand){
        this.name = name;
        this.brand = brand;
    }
    public void speedUp(int speed){
        System.out.println("Name: "+this.name+" Brand: "+this.brand+" with speed "+speed);
    }
}

