/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Vehicle carA = new Vehicle("Vehicle", "BrandA");
        Vehicle carB = new Vehicle("Vehicle", "BrandB");
        carA.speedUp(10);
        carB.speedUp((50));
        Car carC = new Car("CarC", "BrandC");
        carC.speedUp(180);
        carC.speedUp(201);

    }
}
class Vehicle {
    String name;
    String brand;
    public Vehicle(String name, String brand){
        this.name = name;
        this.brand = brand;
    }
    public void speedUp(int speed){
        System.out.println("Name: "+this.name+" Brand: "+this.brand+" with speed "+speed);
    }
}
class Car extends Vehicle {
    public Car(String name, String brand){
        super(name, brand);
    }
    @Override
    public void speedUp(int speed){
        if(speed<200){
            super.speedUp(speed);
        }
        else{
            System.out.println("Cannot Speed Up");
        }
    }
}

