import java.sql.SQLOutput;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Vehicle carA = new Vehicle("Vehicle", "BrandA");
        Vehicle carB = new Vehicle("Vehicle", "BrandB");
        carA.speedUp(10);
        carB.speedUp((50));
        Car carC = new Car("CarC", "BrandC");
        carC.speedUp(180);
        carC.speedUp(201);
        Bus bus = new Bus("Bus", "OOCL");

        Driver tommy = new Driver(carA, "Tommy");
        tommy.speedUp(50);
        Driver jacky = new Driver(carC, "Jacky");
        jacky.speedUp(111);
        Driver baby = new Driver(bus, "Baby");
        baby.speedUp(666);


    }
}
class Driver {
    private final Vehicle vehicle;
    private final String name;
    public Driver(Vehicle vehicle, String name) {
        this.vehicle = vehicle;
        this.name = name;
    }
    public void speedUp(int increase){
        System.out.println("I am "+ name);
        this.vehicle.speedUp(increase);
    }
}
class Bus extends Vehicle {
    public Bus(String name, String brand) {
        super(name, brand);
    }
    @Override
    public void speedUp(int speed){
        System.out.println("I am Driving Bus");
        super.speedUp(speed);
    }

}
class Vehicle {
    String name;
    String brand;
    public Vehicle(String name, String brand){
        this.name = name;
        this.brand = brand;
    }
    public void speedUp(int speed){
        System.out.println("Name: "+this.name+" Brand: "+this.brand+" with speed "+speed);
    }
}
class Car extends Vehicle {
    public Car(String name, String brand){
        super(name, brand);
    }
    @Override
    public void speedUp(int speed){
        System.out.println("I am Driving Car");
        if(speed<200){
            super.speedUp(speed);
        }
        else{
            System.out.println("Cannot Speed Up");
        }
    }
}

